# Site settings
title: 팍팍 클럽
email: dudrnxps1@gmail.com
description: park's Ideas & Blogs

github_username: parkyounghwan
# permalink: /:year/:month/:day/:title/
permalink: /:year/:month/:day/:number/

viewsourceroot: https://github.com/parkyounghwan/parkyounghwan.github.io

disqus_shortname: lixizhi
disqus_url: "http://lixizhi.github.io"
google_analytice: UA-141776052-1

# # Build settings
markdown: kramdown
